# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qLvTnyUxxEtb88Y3BUCFDKb1uZjT3mTi
"""

import pyautogui
import time
import tkinter as tk
from tkinter import *

def screenshot():
  name =  int(round(time.time() * 1000))
  name =  '{}.png'.format(name)
  time.sleep(5)
  img =  pyautogui.screenshot(name)
  img.show()

root =  tk.Tk()
frame =  tk.Frame(root)

frame.pack()
button = tk.Button(
  frame, 
  text = "TAKE SCREENSHOT",
  command = screenshot)

button.pack( side = tk.LEFT)
close = tk.Button(
  frame, 
  text = "QUIT",
  command = quit
  )
close.pack( side = tk.LEFT)

root.mainloop()

